name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "breaking-change"
      - "breaking"
  - title: "✨ New Features"
    labels:
      - "feature"
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "enhance"
      - "improvement"
      - "improve"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    label:
      - "maintenance"
      - "chore"
      - "ci"
  - title: "📝 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
    collapse-after: 3

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "documentation"
      - "docs"
      - "chore"
      - "dependencies"
  default: patch

autolabeler:
  - label: "major"
    title:
      - "/major:/i"
  - label: "minor"
    title:
      - "/minor:/i"
  - label: "patch"
    title:
      - "/patch:/i"
  - label: "breaking-change"
    title:
      - "/breaking-change:/i"
      - "/breaking:/i"
  - label: "feature"
    title:
      - "/feature:/i"
      - "/feat:/i"
  - label: "bugfix"
    title:
      - "/fix:/i"
      - "/bugfix:/i"
      - "/bug:/i"
  - label: "enhancement"
    title:
      - "/enhancement:/i"
      - "/enhance:/i"
      - "/improve:/i"
      - "/improvement:/i"
      - "/refactor:/i"
      - "/performance:/i"
  - label: "chore"
    files:
      - ".github/**/*"
    title:
      - "/maintenance:/i"
      - "/chore:/i"
      - "/ci:/i"
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**/*"
    title:
      - "/documentation:/i"
      - "/docs:/i"
  - label: "dependencies"
    files:
      - "pyproject.toml"
      - "setup.py"
    title:
      - "/dependencies:/i"
      - "/deps:/i"

template: |
  ## Changes

  $CHANGES
