name-template: "v$RESOLVED_VERSION 🚀"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "breaking-change"
      - "breaking"
  - title: "✨ New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📝 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
    collapse-after: 3

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "documentation"
      - "docs"
      - "chore"
      - "dependencies"
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**/*"
  - label: "bug"
    title:
      - "/fix/i"
  - label: "feature"
    title:
      - "/feat/i"
      - "/feature/i"
  - label: "enhancement"
    title:
      - "/enhance/i"
      - "/improve/i"
      - "/improvement/i"
  - label: "dependencies"
    files:
      - "pyproject.toml"
      - "setup.py"
  - label: "chore"
    files:
      - ".github/**/*"
  - label: "breaking-change"
    title:
      - "/breaking/i"

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
