steps:
  # Build the documentation container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/doc-builder', '.']
    
  # Push the container to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/doc-builder']
    
  # Run the container to build documentation
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs create doc-builder-job \
          --image gcr.io/$PROJECT_ID/doc-builder \
          --memory 2Gi \
          --task-timeout 15m \
          --set-env-vars="CLOUD_RUN=1,GCS_BUCKET=$PROJECT_ID-docs" \
          --command="python" \
          --args="docs/build_docs.py,--cloud" \
          --update-env-vars=PYTHONUNBUFFERED=1 \
          --region us-central1 \
          || echo "Job already exists, executing existing job..."
        
        gcloud run jobs execute doc-builder-job --region us-central1 --wait

images:
  - 'gcr.io/$PROJECT_ID/doc-builder'

timeout: 1800s