# Inspired by uv (MIT License)
# https://github.com/astral-sh/uv/blob/f5382c010b24471a6dd6e1ed2fed7c521cf6b87f/.github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    timeout-minutes: 10
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install UV
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version: "0.10.8"
          python-version: "3.10"
          activate-environment: true
          enable-cache: false

      - name: "Ruff format"
        run: uvx ruff@0.14.11 format --diff .

      - name: "Ruff lint"
        run: uvx ruff@0.14.11 check .
