
name: Development Auto-approval
on:
  pull_request:
    branches:
      - develop
    paths:
      - '**'
jobs:
  apply:
    name: Approve Dev PR
    runs-on: ubuntu-latest
    steps:

    - name: Approve pull request
      uses: andrewmusgrave/automatic-pull-request-review@0.0.2
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        event: APPROVE
        body: 'Validation checks passed, PR Approved 🎊'
      if: github.event_name == 'pull_request'