## Here we validate the current PR is already in another branch

on: 
  pull_request:
    branches:
      - master
jobs:
  check-lineage:
    name: Check feature branch is merged into develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check that this commit is merged into develop
        run: if git merge-base --is-ancestor refs/remotes/origin/${{ github.sha }} refs/remotes/origin/develop; then echo "Develop branch is up to date with branch ${{ github.sha }}"; else echo "Develop branch is behind branch ${{ github.sha }}" && exit 1;fi
